# ================= SERVER =================
server.port=${PORT:8080}

# ================= DATABASE =================
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================= COMMON JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ================= JWT =================
careconnect.jwt.secret=careconnect-dev-jwt-secret-key-min-32-chars-long!!
careconnect.jwt.expiration-ms=86400000

# ================= SWAGGER =================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ================= EMAIL CONFIG =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gogisettytulasi@gmail.com
spring.mail.password=lksswbreixkqayyi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================= FILE UPLOAD =================
spring.web.resources.static-locations=file:uploads/

# ================= PROFILE =================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}